# Reactiva JPA (sobreescribe la exclusión del perfil por defecto)
spring.autoconfigure.exclude=

spring.datasource.url=jdbc:postgresql://localhost:5432/blueprints
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
